language: go

go:
    - 1.x
    #- '1.10'
    - 1.11.x
    - master
before_install:
    - go get github.com/mattn/goveralls
script:
    - CVPKG=$(go list ./... | grep -v test | tr '\n' ',') && go test -coverpkg $CVPKG -v -covermode=count -coverprofile=coverage.out ./...
    - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci
after_script:
    - curl -d "repo=github.com/luizvnasc/cwbus-hist" https://goreportcard.com/checks
